[package]
name = "dskvs"
authors.workspace = true
version.workspace = true
description = "Dead simple KVS implementation for/by Rust-lang (to practice to implement KVS)"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
thiserror.workspace = true
